version: '3'

services:
  explorer:
    build:
     context: ../
     dockerfile: Dockerfile
    image: evmos/explorer:latest
    container_name: evmos-explorer
    ports:
      - "4000:80"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
