version: '3'

networks:
  scalar-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24

services:
  ping-pub-explorer:
    networks:
      scalar-network:
        ipv4_address: 10.0.10.28
    image: ping-pub-explorer
    container_name: ping-pub-explorer
    ports:
      - "8080:80"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
